# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [63]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
# from config import gkey
import os

# Import API key
from config import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [64]:
clean_city_data_df= pd.read_csv(
    "Resources/clean_cities.csv", dtype="object", encoding="utf-8")

# Visualize
clean_city_data_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max_Temp,Wind_Speed
0,rikitea,85.0,PF,1595258006.0,57.0,-23.12,-134.97,68.47,13.09
1,bredasdorp,0.0,ZA,1595258006.0,77.0,-34.53,20.04,62.6,6.93
2,bluff,100.0,NZ,1595257969.0,83.0,-46.6,168.33,39.0,3.0
3,butaritari,99.0,KI,1595257715.0,67.0,3.07,172.79,82.76,7.67
4,mecca,30.0,SA,1595257796.0,33.0,21.43,39.83,94.89,6.85
...,...,...,...,...,...,...,...,...,...
579,novosokolniki,100.0,RU,1595258143.0,62.0,56.35,30.16,72.88,3.87
580,homer,75.0,US,1595258143.0,100.0,59.64,-151.55,55.99,2.64
581,ystad,19.0,SE,1595258144.0,48.0,55.43,13.82,66.2,17.22
582,weyburn,100.0,CA,1595258144.0,85.0,49.67,-103.85,61.0,7.09
583,gewane,20.0,ET,1595258144.0,28.0,10.17,40.65,94.57,7.67

In [65]:
#Drop the empty values and clean the table
nan_value = float("NaN")
clean_city_data_df.replace("", nan_value, inplace = True)
clean_city_data_df.dropna(subset = ["Country"], inplace = True)
clean_city_data_df.dropna(subset = ["Cloudiness"], inplace = True)
clean_city_data_df.dropna(subset = ["Date"], inplace = True)
clean_city_data_df.dropna(subset = ["Humidity"], inplace = True)
clean_city_data_df.dropna(subset = ["Lat"], inplace = True)
clean_city_data_df.dropna(subset = ["Lng"], inplace = True)
clean_city_data_df.dropna(subset = ["Max_Temp"], inplace = True)
clean_city_data_df.dropna(subset = ["Wind_Speed"], inplace = True)
clean_city_data_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max_Temp,Wind_Speed
0,rikitea,85.0,PF,1595258006.0,57.0,-23.12,-134.97,68.47,13.09
1,bredasdorp,0.0,ZA,1595258006.0,77.0,-34.53,20.04,62.6,6.93
2,bluff,100.0,NZ,1595257969.0,83.0,-46.6,168.33,39.0,3.0
3,butaritari,99.0,KI,1595257715.0,67.0,3.07,172.79,82.76,7.67
4,mecca,30.0,SA,1595257796.0,33.0,21.43,39.83,94.89,6.85
...,...,...,...,...,...,...,...,...,...
579,novosokolniki,100.0,RU,1595258143.0,62.0,56.35,30.16,72.88,3.87
580,homer,75.0,US,1595258143.0,100.0,59.64,-151.55,55.99,2.64
581,ystad,19.0,SE,1595258144.0,48.0,55.43,13.82,66.2,17.22
582,weyburn,100.0,CA,1595258144.0,85.0,49.67,-103.85,61.0,7.09
583,gewane,20.0,ET,1595258144.0,28.0,10.17,40.65,94.57,7.67

In [66]:
clean_city_data_df.count()

City          579
Cloudiness    579
Country       579
Date          579
Humidity      579
Lat           579
Lng           579
Max_Temp      579
Wind_Speed    579
dtype: int64

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [67]:
gmaps.configure(api_key=g_key)

In [68]:
# Store 'Lat' and 'Lng' into  locations 
locations = clean_city_data_df[["Lat", "Lng"]].astype(float)
humidity = clean_city_data_df["Humidity"].astype(float)
humidity

0       57.0
1       77.0
2       83.0
3       67.0
4       33.0
       ...
579     62.0
580    100.0
581     48.0
582     85.0
583     28.0
Name: Humidity, Length: 579, dtype: float64

In [69]:
#addig heatmap
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)
fig.add_layer(heat_layer)
plt.savefig("Figures/Heat_Map.png")

In [70]:
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [71]:
# Create the Ideal vacation = Tempretaure between 60 and 85 F, wind speed lower than 20mph, and cloudiness <3

ideal_vacation_df = clean_city_data_df[clean_city_data_df["Max_Temp"] > "60"]
ideal_vacation_df = ideal_vacation_df[ideal_vacation_df["Max_Temp"] < "85"]
ideal_vacation_df = ideal_vacation_df[ideal_vacation_df["Wind_Speed"] < "15"]
ideal_vacation_df = ideal_vacation_df[ideal_vacation_df["Cloudiness"] == "0.0"]
ideal_vacation_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max_Temp,Wind_Speed
44,hermanus,0.0,ZA,1595258014.0,70.0,-34.42,19.23,63.0,1.99
53,ponta do sol,0.0,PT,1595258016.0,59.0,32.67,-17.1,73.99,1.05
59,beloha,0.0,MG,1595258017.0,67.0,-25.17,45.05,64.53,13.06
85,durban,0.0,ZA,1595257925.0,64.0,-29.86,31.03,71.6,10.29
120,cavalcante,0.0,BR,1595258028.0,29.0,-13.8,-47.46,78.39,13.24
246,morondava,0.0,MG,1595258055.0,67.0,-20.28,44.28,72.18,10.69
319,ampanihy,0.0,MG,1595258074.0,60.0,-24.7,44.75,66.27,14.58
350,maningrida,0.0,AU,1595258080.0,76.0,-12.07,134.27,67.41,10.04
369,kamarion,0.0,GR,1595258084.0,54.0,36.8,25.82,84.99,13.87
406,richards bay,0.0,ZA,1595258090.0,54.0,-28.78,32.04,70.23,10.49
418,catalao,0.0,BR,1595258093.0,43.0,-18.17,-47.95,75.9,11.7
422,namibe,0.0,AO,1595258094.0,35.0,-15.2,12.15,79.29,12.19
430,sidi bin nur,0.0,TN,1595258096.0,42.0,35.53,10.92,84.2,11.41
445,mangaratiba,0.0,BR,1595258099.0,51.0,-22.96,-44.04,80.6,14.99
470,khromtau,0.0,KZ,1595258122.0,36.0,50.25,58.43,79.16,11.03
491,tigzirt,0.0,DZ,1595258126.0,44.0,36.89,4.12,84.34,11.45
529,standerton,0.0,ZA,1595258134.0,20.0,-26.93,29.24,66.0,1.01
553,mazabuka,0.0,ZM,1595258138.0,33.0,-15.86,27.75,69.98,10.11

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [72]:
maps_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

In [73]:
hotel_df = ideal_vacation_df.loc[:, ["City", "Country", "Lat", "Lng", "Max_Temp"]]

for index, row in hotel_df.iterrows():
    # pull in needed data
    lat = row["Lat"]
    lng = row["Lng"]
    city_name = row["City"]
    params["location"] = f"{lat},{lng}"
    print(f"display the results {index}: {city_name}.")
    response = requests.get(maps_url, params=params).json()
    final_results = response['results']
    
    # save the hotel name to dataframe
    try:
        print(f"Nearby hotel in {city_name} is {final_results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = final_results[0]['name']

    # if there is no hotel available print this
    except (KeyError, IndexError):
        print("Not a hotel... next.")
        
        print("-------End of Search-------")

display the results 44: hermanus.
Nearby hotel in hermanus is Harbour House Hotel.
display the results 53: ponta do sol.
Nearby hotel in ponta do sol is Paul do Mar Aparthotel.
display the results 59: beloha.
Not a hotel... next.
-------End of Search-------
display the results 85: durban.
Nearby hotel in durban is Southern Sun Elangeni & Maharani.
display the results 120: cavalcante.
Nearby hotel in cavalcante is Casa da Zuzu.
display the results 246: morondava.
Nearby hotel in morondava is Palissandre Cote Ouest resort & SPA.
display the results 319: ampanihy.
Not a hotel... next.
-------End of Search-------
display the results 350: maningrida.
Nearby hotel in maningrida is Dhukurrdji Lodge.
display the results 369: kamarion.
Nearby hotel in kamarion is Amorgion Hotel.
display the results 406: richards bay.
Nearby hotel in richards bay is BON Hotel Waterfront Richards Bay.
display the results 418: catalao.
Nearby hotel in catalao is Bristol CatalÃ£o Hotel.
display the results 422: namibe.
Nearby hotel in namibe is iu Hotel Namibe.
display the results 430: sidi bin nur.
Not a hotel... next.
-------End of Search-------
display the results 445: mangaratiba.
Nearby hotel in mangaratiba is Portobello Resort & Safari.
display the results 470: khromtau.
Nearby hotel in khromtau is Gostinitsa Khromit.
display the results 491: tigzirt.
Nearby hotel in tigzirt is HÃ´tel Mizrana.
display the results 529: standerton.
Nearby hotel in standerton is The Log cabin.
display the results 553: mazabuka.
Nearby hotel in mazabuka is Royal Laricio.

In [74]:
hotel_df

,City,Country,Lat,Lng,Max_Temp,Hotel Name
44,hermanus,ZA,-34.42,19.23,63.0,Harbour House Hotel
53,ponta do sol,PT,32.67,-17.1,73.99,Paul do Mar Aparthotel
59,beloha,MG,-25.17,45.05,64.53,NaN
85,durban,ZA,-29.86,31.03,71.6,Southern Sun Elangeni & Maharani
120,cavalcante,BR,-13.8,-47.46,78.39,Casa da Zuzu
246,morondava,MG,-20.28,44.28,72.18,Palissandre Cote Ouest resort & SPA
319,ampanihy,MG,-24.7,44.75,66.27,NaN
350,maningrida,AU,-12.07,134.27,67.41,Dhukurrdji Lodge
369,kamarion,GR,36.8,25.82,84.99,Amorgion Hotel
406,richards bay,ZA,-28.78,32.04,70.23,BON Hotel Waterfront Richards Bay
418,catalao,BR,-18.17,-47.95,75.9,Bristol CatalÃ£o Hotel
422,namibe,AO,-15.2,12.15,79.29,iu Hotel Namibe
430,sidi bin nur,TN,35.53,10.92,84.2,NaN
445,mangaratiba,BR,-22.96,-44.04,80.6,Portobello Resort & Safari
470,khromtau,KZ,50.25,58.43,79.16,Gostinitsa Khromit
491,tigzirt,DZ,36.89,4.12,84.34,HÃ´tel Mizrana
529,standerton,ZA,-26.93,29.24,66.0,The Log cabin
553,mazabuka,ZM,-15.86,27.75,69.98,Royal Laricio

In [75]:
#Replace the emppty values with Nan=N, then clean the data frame from the NaN values
nan_value = float("NaN")
hotel_df.replace("", nan_value, inplace = True)
hotel_df.dropna(subset = ["Hotel Name"], inplace = True)
hotel_df

,City,Country,Lat,Lng,Max_Temp,Hotel Name
44,hermanus,ZA,-34.42,19.23,63.0,Harbour House Hotel
53,ponta do sol,PT,32.67,-17.1,73.99,Paul do Mar Aparthotel
85,durban,ZA,-29.86,31.03,71.6,Southern Sun Elangeni & Maharani
120,cavalcante,BR,-13.8,-47.46,78.39,Casa da Zuzu
246,morondava,MG,-20.28,44.28,72.18,Palissandre Cote Ouest resort & SPA
350,maningrida,AU,-12.07,134.27,67.41,Dhukurrdji Lodge
369,kamarion,GR,36.8,25.82,84.99,Amorgion Hotel
406,richards bay,ZA,-28.78,32.04,70.23,BON Hotel Waterfront Richards Bay
418,catalao,BR,-18.17,-47.95,75.9,Bristol CatalÃ£o Hotel
422,namibe,AO,-15.2,12.15,79.29,iu Hotel Namibe
445,mangaratiba,BR,-22.96,-44.04,80.6,Portobello Resort & Safari
470,khromtau,KZ,50.25,58.43,79.16,Gostinitsa Khromit
491,tigzirt,DZ,36.89,4.12,84.34,HÃ´tel Mizrana
529,standerton,ZA,-26.93,29.24,66.0,The Log cabin
553,mazabuka,ZM,-15.86,27.75,69.98,Royal Laricio

In [76]:
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]
# hotel_info

In [77]:
locations.dtypes

Lat    object
Lng    object
dtype: object

In [82]:
hotel_layer = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(marker_layer)
fig


# fig = gmaps.figure() 
# fig.add_layer(heat_layer)
# fig.add_layer(hotel_layer)
# fig

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [41]:
# locations.dtypes()

TypeError: 'Series' object is not callable