# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [15]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
# from config import gkey
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [16]:
clean_city_data_df= pd.read_csv(
    "Resources/clean_cities.csv", dtype="object", encoding="utf-8")

# Visualize
clean_city_data_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max_Temp,Wind_Speed
0,albany,97.0,US,1595212502.0,94.0,42.6,-73.97,80.01,4.36
1,zeya,100.0,RU,1595212795.0,87.0,53.75,127.27,70.38,10.38
2,vostok,100.0,RU,1595212796.0,30.0,46.49,135.88,81.81,7.85
3,busselton,0.0,AU,1595212625.0,54.0,-33.65,115.33,61.0,10.76
4,castro,0.0,BR,1595212634.0,90.0,-24.79,-50.01,54.81,3.62
...,...,...,...,...,...,...,...,...,...
566,pilar,75.0,BR,1595212927.0,94.0,-9.6,-35.96,71.6,2.24
567,zhigansk,100.0,RU,1595212927.0,69.0,66.77,123.37,63.0,3.51
568,bubaque,100.0,GW,1595212927.0,85.0,11.28,-15.83,79.18,15.61
569,ann arbor,59.0,US,1595212774.0,96.0,42.28,-83.74,73.99,1.99
570,maracaibo,88.0,VE,1595212649.0,79.0,10.63,-71.64,81.97,11.65

In [17]:
#Drop the empty values and clean the table
nan_value = float("NaN")
clean_city_data_df.replace("", nan_value, inplace = True)
clean_city_data_df.dropna(subset = ["Country"], inplace = True)
clean_city_data_df.dropna(subset = ["Cloudiness"], inplace = True)
clean_city_data_df.dropna(subset = ["Date"], inplace = True)
clean_city_data_df.dropna(subset = ["Humidity"], inplace = True)
clean_city_data_df.dropna(subset = ["Lat"], inplace = True)
clean_city_data_df.dropna(subset = ["Lng"], inplace = True)
clean_city_data_df.dropna(subset = ["Max_Temp"], inplace = True)
clean_city_data_df.dropna(subset = ["Wind_Speed"], inplace = True)
clean_city_data_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max_Temp,Wind_Speed
0,albany,97.0,US,1595212502.0,94.0,42.6,-73.97,80.01,4.36
1,zeya,100.0,RU,1595212795.0,87.0,53.75,127.27,70.38,10.38
2,vostok,100.0,RU,1595212796.0,30.0,46.49,135.88,81.81,7.85
3,busselton,0.0,AU,1595212625.0,54.0,-33.65,115.33,61.0,10.76
4,castro,0.0,BR,1595212634.0,90.0,-24.79,-50.01,54.81,3.62
...,...,...,...,...,...,...,...,...,...
566,pilar,75.0,BR,1595212927.0,94.0,-9.6,-35.96,71.6,2.24
567,zhigansk,100.0,RU,1595212927.0,69.0,66.77,123.37,63.0,3.51
568,bubaque,100.0,GW,1595212927.0,85.0,11.28,-15.83,79.18,15.61
569,ann arbor,59.0,US,1595212774.0,96.0,42.28,-83.74,73.99,1.99
570,maracaibo,88.0,VE,1595212649.0,79.0,10.63,-71.64,81.97,11.65

In [18]:
clean_city_data_df.count()

City          566
Cloudiness    566
Country       566
Date          566
Humidity      566
Lat           566
Lng           566
Max_Temp      566
Wind_Speed    566
dtype: int64

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [19]:
gmaps.configure(api_key=g_key)

In [20]:
# Store 'Lat' and 'Lng' into  locations 
locations = clean_city_data_df[["Lat", "Lng"]].astype(float)
humidity = clean_city_data_df["Humidity"].astype(float)
humidity

0      94.0
1      87.0
2      30.0
3      54.0
4      90.0
       ...
566    94.0
567    69.0
568    85.0
569    96.0
570    79.0
Name: Humidity, Length: 566, dtype: float64

In [21]:
#addig heatmap
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
plt.savefig("Figures/Heat_Map.png")

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [22]:
# Create the Ideal vacation = Tempretaure between 60 and 85 F, wind speed lower than 20mph, and cloudiness <3

ideal_vacation_df = clean_city_data_df[clean_city_data_df["Max_Temp"] > "60"]
ideal_vacation_df = ideal_vacation_df[ideal_vacation_df["Max_Temp"] < "85"]
ideal_vacation_df = ideal_vacation_df[ideal_vacation_df["Wind_Speed"] < "15"]
ideal_vacation_df = ideal_vacation_df[ideal_vacation_df["Cloudiness"] == "0.0"]
ideal_vacation_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max_Temp,Wind_Speed
3,busselton,0.0,AU,1595212625.0,54.0,-33.65,115.33,61.0,10.76
23,carnarvon,0.0,AU,1595212712.0,42.0,-24.87,113.63,66.2,14.99
61,flinders,0.0,AU,1595212810.0,41.0,-34.58,150.86,64.0,11.01
239,ballina,0.0,AU,1595212853.0,37.0,-28.87,153.57,73.0,1.99
244,byron bay,0.0,AU,1595212854.0,37.0,-28.65,153.62,73.0,1.99
261,lompoc,0.0,US,1595212777.0,72.0,34.64,-120.46,64.4,12.75
293,celestun,0.0,MX,1595212865.0,76.0,20.87,-90.4,81.73,12.06
348,tiznit,0.0,MA,1595212842.0,38.0,29.58,-9.5,77.18,1.7
369,morondava,0.0,MG,1595212883.0,58.0,-20.28,44.28,65.43,12.15
379,jalu,0.0,LY,1595212863.0,53.0,29.03,21.55,74.05,10.13
401,guerrero negro,0.0,MX,1595212889.0,82.0,27.98,-114.06,69.37,13.24
419,mitsamiouli,0.0,KM,1595212686.0,67.0,-11.38,43.28,76.1,13.2
551,umuarama,0.0,BR,1595212924.0,71.0,-23.77,-53.33,65.01,10.22

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [23]:
maps_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

In [24]:
hotel_df = ideal_vacation_df.loc[:, ["City", "Country", "Lat", "Lng", "Max_Temp"]]

for index, row in hotel_df.iterrows():
    # pull in needed data
    lat = row["Lat"]
    lng = row["Lng"]
    city_name = row["City"]
    params["location"] = f"{lat},{lng}"
    print(f"display the results {index}: {city_name}.")
    response = requests.get(maps_url, params=params).json()
    final_results = response['results']
    
    # save the hotel name to dataframe
    try:
        print(f"Nearby hotel in {city_name} is {final_results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = final_results[0]['name']

    # if there is no hotel available print this
    except (KeyError, IndexError):
        print("Not a hotel... next.")
        
        print("-------End of Search-------")

display the results 3: busselton.
Nearby hotel in busselton is Restawile Motel.
display the results 23: carnarvon.
Nearby hotel in carnarvon is Coral Coast Tourist Park.
display the results 61: flinders.
Nearby hotel in flinders is Lakeview Hotel Motel.
display the results 239: ballina.
Nearby hotel in ballina is Ramada Hotel & Suites by Wyndham Ballina Byron.
display the results 244: byron bay.
Nearby hotel in byron bay is The Park Hotel Motel.
display the results 261: lompoc.
Nearby hotel in lompoc is Embassy Suites by Hilton Lompoc Central Coast.
display the results 293: celestun.
Nearby hotel in celestun is Eco Hotel Flamingo Playa.
display the results 348: tiznit.
Not a hotel... next.
-------End of Search-------
display the results 369: morondava.
Nearby hotel in morondava is Kimony Resort Hotel.
display the results 379: jalu.
Nearby hotel in jalu is Jalu Hotel.
display the results 401: guerrero negro.
Nearby hotel in guerrero negro is Casa Laguna, Bed & Breakfast.
display the results 419: mitsamiouli.
Nearby hotel in mitsamiouli is Moina Lisa.
display the results 551: umuarama.
Nearby hotel in umuarama is HOTEL CAIUÁ.

In [27]:
hotel_df

,City,Country,Lat,Lng,Max_Temp,Hotel Name
3,busselton,AU,-33.65,115.33,61.0,Restawile Motel
23,carnarvon,AU,-24.87,113.63,66.2,Coral Coast Tourist Park
61,flinders,AU,-34.58,150.86,64.0,Lakeview Hotel Motel
239,ballina,AU,-28.87,153.57,73.0,Ramada Hotel & Suites by Wyndham Ballina Byron
244,byron bay,AU,-28.65,153.62,73.0,The Park Hotel Motel
261,lompoc,US,34.64,-120.46,64.4,Embassy Suites by Hilton Lompoc Central Coast
293,celestun,MX,20.87,-90.4,81.73,Eco Hotel Flamingo Playa
369,morondava,MG,-20.28,44.28,65.43,Kimony Resort Hotel
379,jalu,LY,29.03,21.55,74.05,Jalu Hotel
401,guerrero negro,MX,27.98,-114.06,69.37,"Casa Laguna, Bed & Breakfast"
419,mitsamiouli,KM,-11.38,43.28,76.1,Moina Lisa
551,umuarama,BR,-23.77,-53.33,65.01,HOTEL CAIUÁ

In [28]:
#Replace the emppty values with Nan=N, then clean the data frame from the NaN values
nan_value = float("NaN")
hotel_df.replace("", nan_value, inplace = True)
hotel_df.dropna(subset = ["Hotel Name"], inplace = True)
hotel_df

,City,Country,Lat,Lng,Max_Temp,Hotel Name
3,busselton,AU,-33.65,115.33,61.0,Restawile Motel
23,carnarvon,AU,-24.87,113.63,66.2,Coral Coast Tourist Park
61,flinders,AU,-34.58,150.86,64.0,Lakeview Hotel Motel
239,ballina,AU,-28.87,153.57,73.0,Ramada Hotel & Suites by Wyndham Ballina Byron
244,byron bay,AU,-28.65,153.62,73.0,The Park Hotel Motel
261,lompoc,US,34.64,-120.46,64.4,Embassy Suites by Hilton Lompoc Central Coast
293,celestun,MX,20.87,-90.4,81.73,Eco Hotel Flamingo Playa
369,morondava,MG,-20.28,44.28,65.43,Kimony Resort Hotel
379,jalu,LY,29.03,21.55,74.05,Jalu Hotel
401,guerrero negro,MX,27.98,-114.06,69.37,"Casa Laguna, Bed & Breakfast"
419,mitsamiouli,KM,-11.38,43.28,76.1,Moina Lisa
551,umuarama,BR,-23.77,-53.33,65.01,HOTEL CAIUÁ

In [29]:
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]
hotel_info

['\n<dl>\n<dt>Name</dt><dd>Restawile Motel</dd>\n<dt>City</dt><dd>busselton</dd>\n<dt>Country</dt><dd>AU</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Coral Coast Tourist Park</dd>\n<dt>City</dt><dd>carnarvon</dd>\n<dt>Country</dt><dd>AU</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Lakeview Hotel Motel</dd>\n<dt>City</dt><dd>flinders</dd>\n<dt>Country</dt><dd>AU</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Ramada Hotel & Suites by Wyndham Ballina Byron</dd>\n<dt>City</dt><dd>ballina</dd>\n<dt>Country</dt><dd>AU</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>The Park Hotel Motel</dd>\n<dt>City</dt><dd>byron bay</dd>\n<dt>Country</dt><dd>AU</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Embassy Suites by Hilton Lompoc Central Coast</dd>\n<dt>City</dt><dd>lompoc</dd>\n<dt>Country</dt><dd>US</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Eco Hotel Flamingo Playa</dd>\n<dt>City</dt><dd>celestun</dd>\n<dt>Country</dt><dd>MX</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Kimony Resort Hotel</dd>\n<dt>City</dt><dd>morondava</dd>\n<dt>Country</dt><dd>MG</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Jalu Hotel</dd>\n<dt>City</dt><dd>jalu</dd>\n<dt>Country</dt><dd>LY</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Casa Laguna, Bed & Breakfast</dd>\n<dt>City</dt><dd>guerrero negro</dd>\n<dt>Country</dt><dd>MX</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Moina Lisa</dd>\n<dt>City</dt><dd>mitsamiouli</dd>\n<dt>Country</dt><dd>KM</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>HOTEL CAIUÁ</dd>\n<dt>City</dt><dd>umuarama</dd>\n<dt>Country</dt><dd>BR</dd>\n</dl>\n']

In [30]:
hotel_layer = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig = gmaps.figure() 
fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)
fig

TypeError: unsupported operand type(s) for -: 'str' and 'str'